services:
  - type: web
    name: daignoseai
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: daignoseai-db
          property: connectionString
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true

  - type: pserv
    name: daignoseai-db
    env: postgres
    plan: starter
    disk:
      name: data
      mountPath: /var/lib/postgresql/data
      sizeGB: 1